blank_issues_enabled: false
contact_links:
  - name: SisApp Website
    url: https://github.com/fahrizalm14/osist-test#readme
    about: Details & Docs for Ragdata's Public Projects

  - name: Security Report Email
    email: fahrizalm14@gmail.com
    about: For reports of SERIOUS Security Flaws ONLY
